use super::Strings;

pub(super) const STRINGS: Strings = Strings {
    window_title: "Codex Usage",
    refresh: "Actualiser",
    update_frequency: "Fréquence de mise à jour",
    one_minute: "1 minute",
    five_minutes: "5 minutes",
    fifteen_minutes: "15 minutes",
    one_hour: "1 heure",
    adaptive: "Adaptatif",
    models: "Modeles",
    claude_code_model: "Claude Code",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    settings: "Paramètres",
    start_with_windows: "Démarrer avec Windows",
    reset_position: "Réinitialiser la position",
    show_drag_handle: "Afficher la poignée de déplacement",
    enable_codex_mcp: "Activer l’intégration MCP",
    language: "Langue",
    system_default: "Par défaut du système",
    check_for_updates: "Vérifier les mises à jour",
    open_log_file: "Ouvrir le fichier journal",
    checking_for_updates: "Vérification des mises à jour...",
    updates: "Mises à jour",
    update_in_progress: "Une vérification de mise à jour est déjà en cours.",
    up_to_date: "Vous utilisez déjà la version la plus récente.",
    up_to_date_short: "À jour",
    update_failed: "Impossible d'effectuer la mise à jour automatiquement",
    applying_update: "Application de la mise à jour...",
    update_to: "Mettre à jour vers",
    update_available: "Mise à jour disponible",
    update_prompt_now: "La version {version} est disponible. Voulez-vous mettre à jour maintenant ?",
    exit: "Quitter",
    show_widget: "Afficher le widget",
    credits: "Crédits",
    credit_display: "Crédits / Luna Reserve",
    credit_always: "Toujours",
    credit_when_needed: "Si nécessaire",
    credit_off: "Désactivé",
    credit_left: "Gauche",
    credit_right: "Droite",
    credit_usd_estimate: "USD",
    session_window: "5h",
    weekly_window: "7d",
    now: "maintenant",
    day_suffix: "j",
    hour_suffix: "h",
    minute_suffix: "m",
    token_expired_title: "Erreur d'authentification",
    token_expired_body: "L’authentification du CLI Claude Code est requise ; la connexion à l’application de bureau Claude ne suffit pas. Exécutez 'claude' dans un terminal, puis utilisez '/login' et suivez les instructions. Ensuite, actualisez ou redémarrez cette application.",
    codex_token_expired_title: "Erreur d'authentification Codex",
    codex_token_expired_body: "Executez 'codex' dans un terminal et suivez les instructions de connexion. Ensuite, actualisez ou redemarrez cette application.",
    antigravity_token_expired_title: "Erreur d'authentification Antigravity",
    antigravity_token_expired_body: "Ouvrez Antigravity et reconnectez-vous. Ensuite, actualisez ou redemarrez cette application.",
    codex_window_title: "Moniteur d'utilisation Codex",
    antigravity_window_title: "Moniteur d'utilisation Antigravity",
    second_suffix: "s",
};
