use super::Strings;

pub(super) const STRINGS: Strings = Strings {
    window_title: "Codex Usage",
    refresh: "更新",
    update_frequency: "更新間隔",
    one_minute: "1分",
    five_minutes: "5分",
    fifteen_minutes: "15分",
    one_hour: "1時間",
    adaptive: "自動調整",
    models: "モデル",
    claude_code_model: "Claude Code",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    settings: "設定",
    start_with_windows: "Windows と同時に開始",
    reset_position: "位置をリセット",
    show_drag_handle: "ドラッグハンドルを表示",
    enable_codex_mcp: "MCP 連携を有効にする",
    language: "言語",
    system_default: "システム既定",
    check_for_updates: "更新を確認",
    open_log_file: "ログファイルを開く",
    checking_for_updates: "更新を確認しています...",
    updates: "更新",
    update_in_progress: "更新確認は既に実行中です。",
    up_to_date: "既に最新バージョンです。",
    up_to_date_short: "最新です",
    update_failed: "自動更新を完了できませんでした",
    applying_update: "更新を適用しています...",
    update_to: "更新先",
    update_available: "更新が利用可能です",
    update_prompt_now: "バージョン {version} が利用可能です。今すぐ更新しますか？",
    exit: "終了",
    show_widget: "ウィジェットを表示",
    credits: "クレジット",
    credit_display: "クレジット / Luna Reserve",
    credit_always: "常に",
    credit_when_needed: "必要な場合",
    credit_off: "オフ",
    credit_left: "左",
    credit_right: "右",
    credit_usd_estimate: "USD",
    session_window: "5h",
    weekly_window: "7d",
    now: "今",
    day_suffix: "日",
    hour_suffix: "時間",
    minute_suffix: "分",
    token_expired_title: "認証エラー",
    token_expired_body: "Claude Code CLI の認証が必要です。Claude デスクトップアプリにサインインしているだけでは不十分です。ターミナルで 'claude' を実行し、'/login' を使って案内に従ってください。その後、このアプリを更新するか再起動してください。",
    codex_token_expired_title: "Codex 認証エラー",
    codex_token_expired_body: "ターミナルで 'codex' を実行し、サインインの案内に従ってください。その後、このアプリを更新または再起動してください。",
    antigravity_token_expired_title: "Antigravity 認証エラー",
    antigravity_token_expired_body: "Antigravity を開いて再度サインインしてください。その後、このアプリを更新するか再起動してください。",
    codex_window_title: "Codex 使用量モニター",
    antigravity_window_title: "Antigravity 使用量モニター",
    second_suffix: "秒",
};
