use super::Strings;

pub(super) const STRINGS: Strings = Strings {
    window_title: "Codex Usage",
    refresh: "Atualizar",
    update_frequency: "Frequência de Atualização",
    one_minute: "1 Minuto",
    five_minutes: "5 Minutos",
    fifteen_minutes: "15 Minutos",
    one_hour: "1 Hora",
    adaptive: "Adaptativo",
    models: "Modelos",
    claude_code_model: "Claude Code",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    settings: "Configurações",
    start_with_windows: "Iniciar com o Windows",
    reset_position: "Redefinir Posição",
    show_drag_handle: "Mostrar alça de arraste",
    enable_codex_mcp: "Ativar integração MCP",
    language: "Idioma",
    system_default: "Padrão do Sistema",
    check_for_updates: "Busca atualizações",
    open_log_file: "Abrir arquivo de log",
    checking_for_updates: "Buscando por atualizações...",
    updates: "Atualizações",
    update_in_progress: "Uma verificação de atualização já está em andamento.",
    up_to_date: "Você já tem a versão mais recente.",
    up_to_date_short: "Atualizado",
    update_failed: "Não foi possível atualizar automaticamente",
    applying_update: "Aplicando atualização...",
    update_to: "Atualizar para",
    update_available: "Atualização disponível",
    update_prompt_now: "Versão {version} está disponível. Deseja atualizar agora?",
    exit: "Sair",
    show_widget: "Exibir Widget",
    credits: "Créditos",
    credit_display: "Créditos / Luna Reserve",
    credit_always: "Sempre",
    credit_when_needed: "Quando necessário",
    credit_off: "Desativado",
    credit_left: "Esquerda",
    credit_right: "Direita",
    credit_usd_estimate: "USD",
    session_window: "5h",
    weekly_window: "7d",
    now: "agora",
    day_suffix: "d",
    hour_suffix: "h",
    minute_suffix: "m",
    second_suffix: "s",
    token_expired_title: "Erro de Autenticação do Claude Code",
    token_expired_body: "A autenticação da CLI do Claude Code é necessária; entrar no aplicativo Claude para desktop não é suficiente. Execute 'claude' em um terminal, use '/login' e siga as instruções. Depois disso, atualize ou reinicie este aplicativo.",
    codex_token_expired_title: "Erro de Autenticação do Codex",
    codex_token_expired_body: "Execute 'codex' em um terminal e siga as instruções de login. Depois disso, atualize ou reinicie este aplicativo.",
    antigravity_token_expired_title: "Erro de Autenticação do Antigravity",
    antigravity_token_expired_body: "Abra o Antigravity e entre novamente. Depois disso, atualize ou reinicie este aplicativo.",
    codex_window_title: "Monitor de uso do Codex",
    antigravity_window_title: "Monitor de uso do Antigravity",
};
