use super::Strings;

pub(super) const STRINGS: Strings = Strings {
    window_title: "Codex Usage",
    refresh: "Actualizar",
    update_frequency: "Frecuencia de actualización",
    one_minute: "1 minuto",
    five_minutes: "5 minutos",
    fifteen_minutes: "15 minutos",
    one_hour: "1 hora",
    adaptive: "Adaptativo",
    models: "Modelos",
    claude_code_model: "Claude Code",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    settings: "Configuración",
    start_with_windows: "Iniciar con Windows",
    reset_position: "Restablecer posición",
    show_drag_handle: "Mostrar control de arrastre",
    enable_codex_mcp: "Activar integración MCP",
    language: "Idioma",
    system_default: "Predeterminado del sistema",
    check_for_updates: "Buscar actualizaciones",
    open_log_file: "Abrir archivo de registro",
    checking_for_updates: "Buscando actualizaciones...",
    updates: "Actualizaciones",
    update_in_progress: "Ya hay una comprobación de actualización en curso.",
    up_to_date: "Ya tienes la versión más reciente.",
    up_to_date_short: "Actualizado",
    update_failed: "No se pudo actualizar automáticamente",
    applying_update: "Aplicando actualización...",
    update_to: "Actualizar a",
    update_available: "Actualización disponible",
    update_prompt_now: "La versión {version} está disponible. ¿Quieres actualizar ahora?",
    exit: "Salir",
    show_widget: "Mostrar widget",
    credits: "Créditos",
    credit_display: "Créditos / Luna Reserve",
    credit_always: "Siempre",
    credit_when_needed: "Cuando sea necesario",
    credit_off: "Desactivado",
    credit_left: "Izquierda",
    credit_right: "Derecha",
    credit_usd_estimate: "USD",
    session_window: "5h",
    weekly_window: "7d",
    now: "ahora",
    day_suffix: "d",
    hour_suffix: "h",
    minute_suffix: "m",
    token_expired_title: "Error de autenticación",
    token_expired_body: "Se requiere autenticación de la CLI de Claude Code; iniciar sesión en la aplicación de escritorio de Claude no es suficiente. Ejecuta 'claude' en una terminal, luego usa '/login' y sigue las indicaciones. Después, actualiza o reinicia esta aplicación.",
    codex_token_expired_title: "Error de autenticacion de Codex",
    codex_token_expired_body: "Ejecuta 'codex' en una terminal y sigue las indicaciones de inicio de sesion. Despues, actualiza o reinicia esta aplicacion.",
    antigravity_token_expired_title: "Error de autenticacion de Antigravity",
    antigravity_token_expired_body: "Abre Antigravity e inicia sesion otra vez. Despues, actualiza o reinicia esta aplicacion.",
    codex_window_title: "Monitor de uso de Codex",
    antigravity_window_title: "Monitor de uso de Antigravity",
    second_suffix: "s",
};
